// ===========================================================
// Irrigation Advisory System for Sugarcane Crop - Shared JS
// ===========================================================

// Highlight the active nav link based on current page
document.addEventListener('DOMContentLoaded', () => {
  const current = window.location.pathname.split('/').pop() || 'index.html';
  document.querySelectorAll('nav ul li a').forEach(link => {
    const href = link.getAttribute('href');
    if (href === current) link.classList.add('active');
  });

  // Simulated live sensor readout on Home/Sensors pages
  const soilEl = document.getElementById('live-soil');
  const tempEl = document.getElementById('live-temp');
  const humEl = document.getElementById('live-humidity');
  if (soilEl && tempEl && humEl) {
    updateSimulatedReadings(soilEl, tempEl, humEl);
    setInterval(() => updateSimulatedReadings(soilEl, tempEl, humEl), 4000);
  }

  // Contact form (front-end only, no backend configured)
  const contactForm = document.getElementById('contact-form');
  if (contactForm) {
    contactForm.addEventListener('submit', (e) => {
      e.preventDefault();
      const msg = document.getElementById('contact-status');
      msg.textContent = 'Thank you! Your message has been recorded (demo form — connect a backend or form service such as Formspree to receive real submissions).';
      msg.style.display = 'block';
      contactForm.reset();
    });
  }
});

function updateSimulatedReadings(soilEl, tempEl, humEl) {
  const soil = (20 + Math.random() * 45).toFixed(1);
  const temp = (24 + Math.random() * 12).toFixed(1);
  const hum = (40 + Math.random() * 40).toFixed(1);
  soilEl.textContent = soil + '%';
  tempEl.textContent = temp + '°C';
  humEl.textContent = hum + '%';
}

// ---------- AI Advisory rule-based engine (advisory.html) ----------
function runAdvisory(event) {
  event.preventDefault();

  const soilMoisture = parseFloat(document.getElementById('soilMoisture').value);
  const temperature = parseFloat(document.getElementById('temperature').value);
  const humidity = parseFloat(document.getElementById('humidity').value);
  const rainForecast = document.getElementById('rainForecast').value;
  const growthStage = document.getElementById('growthStage').value;

  const resultBox = document.getElementById('result-box');

  if (isNaN(soilMoisture) || isNaN(temperature) || isNaN(humidity)) {
    resultBox.className = 'alert';
    resultBox.innerHTML = '<h3>Input Error</h3><p>Please enter valid numeric values for soil moisture, temperature, and humidity.</p>';
    return;
  }

  // Growth-stage moisture thresholds (simplified, based on typical sugarcane
  // irrigation guidance: germination and grand growth stages are most water-sensitive)
  const thresholds = {
    germination: { low: 65, high: 80 },
    tillering:   { low: 60, high: 75 },
    grand_growth:{ low: 70, high: 85 },
    maturity:    { low: 45, high: 60 }
  };

  const t = thresholds[growthStage] || thresholds.tillering;

  let verdict, cssClass, litersPerHa, notes;

  if (rainForecast === 'yes' && soilMoisture >= t.low - 10) {
    verdict = 'No Irrigation Needed';
    cssClass = 'ok';
    litersPerHa = 0;
    notes = 'Rainfall is forecast within 24 hours and soil moisture is adequate. Delay irrigation to avoid waterlogging and nutrient leaching.';
  } else if (soilMoisture < t.low) {
    const deficit = t.low - soilMoisture;
    litersPerHa = Math.round(deficit * 450); // simplified estimate
    verdict = 'Irrigation Recommended';
    cssClass = deficit > 15 ? 'alert' : 'warn';
    notes = `Soil moisture is below the optimal range (${t.low}–${t.high}%) for the ${growthStage.replace('_',' ')} stage. `;
    if (temperature > 33) notes += 'High temperature increases crop water demand — irrigate soon. ';
    if (humidity < 40) notes += 'Low humidity accelerates evapotranspiration.';
  } else if (soilMoisture > t.high) {
    verdict = 'Hold Irrigation — Risk of Waterlogging';
    cssClass = 'warn';
    litersPerHa = 0;
    notes = `Soil moisture (${soilMoisture}%) exceeds the optimal range (${t.low}–${t.high}%) for this stage. Excess water can cause root damage and nutrient loss. Allow soil to drain before next irrigation.`;
  } else {
    verdict = 'Soil Moisture Optimal';
    cssClass = 'ok';
    litersPerHa = 0;
    notes = `Soil moisture is within the optimal range (${t.low}–${t.high}%) for the ${growthStage.replace('_',' ')} stage. Continue routine sensor monitoring.`;
  }

  resultBox.className = cssClass;
  resultBox.innerHTML = `
    <h3>${verdict}</h3>
    <p>${notes}</p>
    ${litersPerHa > 0 ? `<p><strong>Estimated irrigation requirement:</strong> ~${litersPerHa.toLocaleString()} liters/hectare</p>` : ''}
    <p class="helper-text">Advisory generated by rule-based AI logic using inputs: soil moisture ${soilMoisture}%, temperature ${temperature}°C, humidity ${humidity}%, growth stage: ${growthStage.replace('_',' ')}, rain forecast: ${rainForecast}.</p>
  `;
  resultBox.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}
